name: Tests_cd
on:
  push:
    branches: [ 'dev' ]
jobs:
  open_PR:
    name: Open_PullRequest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4

        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          commit-message: Automated PR
          branch: dev
          base: homolog
          title: 'Automated - homolog to release'
          reviewers: TiagoMPereira
