name: PR_Homolog
on:
  push:
    branches: [ 'dev' ]

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: "dev"                                 # If blank, default: triggered branch
        destination_branch: "homolog"                      # If blank, default: master
        pr_title: "Pulling dev into homolog"              # Title of pull request
        pr_body: ":crown: *An automated PR*"              # Full markdown support, requires pr_title to be set
        pr_assignee: "TiagoPereira-4i"                         # Comma-separated list (no spaces)
        pr_label: "auto-pr"                               # Comma-separated list (no spaces)
        pr_allow_empty: true                              # Creates pull request even if there are no changes
        github_token: ${{ secrets.ACCESS_TOKEN }}